package bundle

import (
	"encoding/hex"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"csip-tls-test/internal/evidence/capture"
	"csip-tls-test/internal/evidence/keylog"
)

// --- synthetic TLS ClientHello fixture -------------------------------------

// clientHelloRecord builds the smallest TLS record tlsdis will parse as a
// ClientHello carrying exactly `random` — client_version, random, an empty
// session id, one cipher suite, and null-only compression. No extensions:
// parseClientHello treats them as optional once the cursor is empty.
func clientHelloRecord(random [32]byte) []byte {
	body := []byte{0x03, 0x03} // legacy_version = TLS 1.2
	body = append(body, random[:]...)
	body = append(body, 0x00)       // session_id: length 0
	body = append(body, 0x00, 0x02) // cipher_suites: length 2
	body = append(body, 0xC0, 0x2B) // TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
	body = append(body, 0x01, 0x00) // compression_methods: [null]

	hs := append([]byte{0x01, byte(len(body) >> 16), byte(len(body) >> 8), byte(len(body))}, body...)
	rec := append([]byte{0x16, 0x03, 0x01, byte(len(hs) >> 8), byte(len(hs))}, hs...)
	return rec
}

// writeKeylogCapture lays down one packet per random, each on its own TCP
// 4-tuple (distinct source port), carrying that session's ClientHello. No
// handshake is needed: netdis.Assembler opens a stream generation on a
// flow's first frame (reassembly.go, `fresh := st == nil || ...`), so a bare
// data packet is enough to put the ClientHello where captureClientRandoms
// looks for it.
func writeKeylogCapture(t *testing.T, path string, randoms [][32]byte) {
	t.Helper()
	w := newPcapngWriter()
	base := uint64(1_700_000_000_000_000)
	for i, r := range randoms {
		sport := uint16(50000 + i)
		w.packet(base+uint64(i)*1000,
			ethIPv4TCP(desktopIP, gatewayIP, sport, 443, 1000, 0x18, clientHelloRecord(r)))
	}
	if err := os.WriteFile(path, w.buf, 0o644); err != nil {
		t.Fatal(err)
	}
}

func randomOf(b byte) [32]byte {
	var r [32]byte
	for i := range r {
		r[i] = b
	}
	return r
}

// --- captureClientRandoms ---------------------------------------------------

func TestCaptureClientRandomsFindsEveryClientHello(t *testing.T) {
	dir := t.TempDir()
	r1, r2, r3 := randomOf(0x11), randomOf(0x22), randomOf(0x33)
	capturePath := filepath.Join(dir, "run.pcapng")
	writeKeylogCapture(t, capturePath, [][32]byte{r1, r2, r3})

	got, err := captureClientRandoms(capturePath)
	if err != nil {
		t.Fatalf("captureClientRandoms: %v", err)
	}
	for _, r := range []([32]byte){r1, r2, r3} {
		if !got[hex.EncodeToString(r[:])] {
			t.Errorf("captureClientRandoms missed %x", r)
		}
	}
	if len(got) != 3 {
		t.Errorf("captureClientRandoms = %v, want exactly 3 sessions", got)
	}
}

// --- writeFilteredKeyLog ----------------------------------------------------

// TestWriteFilteredKeyLogScopesToCapture is the mechanism this file exists
// for: a shared key log naming THREE sessions, a capture holding only ONE of
// them, and only that one session's lines — every label — surviving into the
// bundle. This is the test that must FAIL if Write ever goes back to
// copying the source key log verbatim (see the mutation-verify note in the
// task report).
func TestWriteFilteredKeyLogScopesToCapture(t *testing.T) {
	dir := t.TempDir()
	inCapture, otherLeg, otherCampaign := randomOf(0x22), randomOf(0x11), randomOf(0x33)

	capturePath := filepath.Join(dir, "run.pcapng")
	writeKeylogCapture(t, capturePath, [][32]byte{inCapture})

	src := filepath.Join(dir, "bench-shared.keylog")
	lines := []string{
		"# SSL/TLS secrets log file, generated by the bench",
		"",
		"CLIENT_RANDOM " + hex.EncodeToString(otherLeg[:]) + " " + strings.Repeat("aa", 48),
		"CLIENT_HANDSHAKE_TRAFFIC_SECRET " + hex.EncodeToString(inCapture[:]) + " " + strings.Repeat("bb", 32),
		"SERVER_HANDSHAKE_TRAFFIC_SECRET " + hex.EncodeToString(inCapture[:]) + " " + strings.Repeat("cc", 32),
		"CLIENT_TRAFFIC_SECRET_0 " + hex.EncodeToString(inCapture[:]) + " " + strings.Repeat("dd", 32),
		"SERVER_TRAFFIC_SECRET_0 " + hex.EncodeToString(inCapture[:]) + " " + strings.Repeat("ee", 32),
		"EXPORTER_SECRET " + hex.EncodeToString(inCapture[:]) + " " + strings.Repeat("ff", 32),
		"CLIENT_RANDOM " + hex.EncodeToString(otherCampaign[:]) + " " + strings.Repeat("11", 48),
		"this line has way too many fields to be a key-log entry ever",
	}
	if err := os.WriteFile(src, []byte(strings.Join(lines, "\n")+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	dst := filepath.Join(dir, "out", "capture.keylog")
	counts, err := writeFilteredKeyLog(src, capturePath, dst)
	if err != nil {
		t.Fatalf("writeFilteredKeyLog: %v", err)
	}
	// inCapture's 5 labels kept; otherLeg + otherCampaign + the garbage line
	// dropped.
	if counts.Kept != 5 {
		t.Errorf("Kept = %d, want 5", counts.Kept)
	}
	if counts.Dropped != 3 {
		t.Errorf("Dropped = %d, want 3", counts.Dropped)
	}

	raw, err := os.ReadFile(dst)
	if err != nil {
		t.Fatal(err)
	}
	got := string(raw)
	if strings.Contains(got, hex.EncodeToString(otherLeg[:])) {
		t.Error("filtered key log carries a session from OUTSIDE this bundle's capture (otherLeg)")
	}
	if strings.Contains(got, hex.EncodeToString(otherCampaign[:])) {
		t.Error("filtered key log carries a session from OUTSIDE this bundle's capture (otherCampaign)")
	}
	for _, label := range []string{
		"CLIENT_HANDSHAKE_TRAFFIC_SECRET", "SERVER_HANDSHAKE_TRAFFIC_SECRET",
		"CLIENT_TRAFFIC_SECRET_0", "SERVER_TRAFFIC_SECRET_0", "EXPORTER_SECRET",
	} {
		if !strings.Contains(got, label+" "+hex.EncodeToString(inCapture[:])) {
			t.Errorf("filtered key log dropped %s for the session that IS in the capture", label)
		}
	}

	// The filtered file is itself a well-formed key log carrying exactly one
	// session, with no orphans against the capture it was scoped to.
	kl, err := keylog.Open(dst)
	if err != nil {
		t.Fatalf("filtered key log does not parse: %v", err)
	}
	if sessions := kl.Sessions(); len(sessions) != 1 || sessions[0] != hex.EncodeToString(inCapture[:]) {
		t.Errorf("Sessions() = %v, want just inCapture", sessions)
	}
	randoms, err := captureClientRandoms(capturePath)
	if err != nil {
		t.Fatalf("captureClientRandoms: %v", err)
	}
	if orphans := keylog.Orphans(kl, randoms); len(orphans) != 0 {
		t.Errorf("Orphans = %v, want none after filtering", orphans)
	}
}

// TestWriteFilteredKeyLogMalformedLineNotFatal is item 3's malformed-line
// requirement in isolation: one bad line among good ones must be dropped and
// counted, and must not abort the write of the lines around it.
func TestWriteFilteredKeyLogMalformedLineNotFatal(t *testing.T) {
	dir := t.TempDir()
	r := randomOf(0x44)
	capturePath := filepath.Join(dir, "run.pcapng")
	writeKeylogCapture(t, capturePath, [][32]byte{r})

	src := filepath.Join(dir, "shared.keylog")
	lines := []string{
		"CLIENT_RANDOM " + hex.EncodeToString(r[:]) + " " + strings.Repeat("aa", 48),
		"not a keylog line at all",
		"CLIENT_RANDOM zznothex " + strings.Repeat("bb", 48), // client random not hex
	}
	if err := os.WriteFile(src, []byte(strings.Join(lines, "\n")+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	dst := filepath.Join(dir, "out.keylog")
	counts, err := writeFilteredKeyLog(src, capturePath, dst)
	if err != nil {
		t.Fatalf("writeFilteredKeyLog must not fail on a malformed line: %v", err)
	}
	if counts.Kept != 1 {
		t.Errorf("Kept = %d, want 1", counts.Kept)
	}
	if counts.Dropped != 2 {
		t.Errorf("Dropped = %d, want 2", counts.Dropped)
	}
	raw, err := os.ReadFile(dst)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(raw), hex.EncodeToString(r[:])) {
		t.Error("the well-formed, in-capture line did not survive alongside the malformed ones")
	}
}

// TestWriteFilteredKeyLogEmptySource: an empty source key log produces an
// empty destination file and no error, from a scan that never has anything
// to keep or drop.
func TestWriteFilteredKeyLogEmptySource(t *testing.T) {
	dir := t.TempDir()
	src := filepath.Join(dir, "empty.keylog")
	if err := os.WriteFile(src, nil, 0o600); err != nil {
		t.Fatal(err)
	}
	capturePath := filepath.Join(dir, "run.pcapng")
	writeKeylogCapture(t, capturePath, nil)

	dst := filepath.Join(dir, "out.keylog")
	counts, err := writeFilteredKeyLog(src, capturePath, dst)
	if err != nil {
		t.Fatalf("writeFilteredKeyLog: %v", err)
	}
	if counts.Kept != 0 || counts.Dropped != 0 {
		t.Errorf("counts = %+v, want zero", counts)
	}
	raw, err := os.ReadFile(dst)
	if err != nil {
		t.Fatal(err)
	}
	if len(raw) != 0 {
		t.Errorf("filtered file = %q, want empty", raw)
	}
}

// TestWriteFilteredKeyLogNoCaptureKeepsNothing: SetKeyLog with no capture at
// all must not ship anything — every kept line asserts "this session is in
// the bundle's own capture", and with no capture there is nothing to check
// that assertion against.
func TestWriteFilteredKeyLogNoCaptureKeepsNothing(t *testing.T) {
	dir := t.TempDir()
	r := randomOf(0x55)
	src := filepath.Join(dir, "shared.keylog")
	line := "CLIENT_RANDOM " + hex.EncodeToString(r[:]) + " " + strings.Repeat("aa", 48) + "\n"
	if err := os.WriteFile(src, []byte(line), 0o600); err != nil {
		t.Fatal(err)
	}

	dst := filepath.Join(dir, "out.keylog")
	counts, err := writeFilteredKeyLog(src, "", dst)
	if err != nil {
		t.Fatalf("writeFilteredKeyLog: %v", err)
	}
	if counts.Kept != 0 || counts.Dropped != 1 {
		t.Errorf("counts = %+v, want Kept=0 Dropped=1", counts)
	}
	raw, err := os.ReadFile(dst)
	if err != nil {
		t.Fatal(err)
	}
	if len(raw) != 0 {
		t.Errorf("filtered file = %q, want empty", raw)
	}
}

// --- end-to-end through Builder.Write ---------------------------------------

// TestBundleWriteFiltersKeyLogToCapture exercises the actual call site
// (write.go) rather than writeFilteredKeyLog directly: a bundle built from a
// capture holding one session and a key log naming two must ship only the
// one the capture actually contains, and must record the kept/dropped
// counts on the Builder.
func TestBundleWriteFiltersKeyLogToCapture(t *testing.T) {
	work := t.TempDir()
	inScope, outOfScope := randomOf(0xAA), randomOf(0xBB)

	capturePath := filepath.Join(work, "run.pcapng")
	writeKeylogCapture(t, capturePath, [][32]byte{inScope})

	keylogPath := filepath.Join(work, "bench-shared.keylog")
	lines := []string{
		"CLIENT_RANDOM " + hex.EncodeToString(inScope[:]) + " " + strings.Repeat("aa", 48),
		"CLIENT_RANDOM " + hex.EncodeToString(outOfScope[:]) + " " + strings.Repeat("bb", 48),
	}
	if err := os.WriteFile(keylogPath, []byte(strings.Join(lines, "\n")+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	b := NewBuilder(RunMeta{Tool: "evidence-engine-test", Operator: "bench"})
	b.SetCapture(capture.Summary{Tool: "dumpcap", Format: "pcapng"}, capturePath)
	b.SetKeyLog(keylogPath)
	b.AddCase(TestCaseResult{ID: "KL-1", Title: "keylog scoping fixture", Verdict: Pass})

	dir := filepath.Join(work, "bundle")
	bd, err := b.Write(dir)
	if err != nil {
		t.Fatalf("Write: %v", err)
	}

	if got := b.KeyLogLinesKept(); got != 1 {
		t.Errorf("KeyLogLinesKept() = %d, want 1", got)
	}
	if got := b.KeyLogLinesDropped(); got != 1 {
		t.Errorf("KeyLogLinesDropped() = %d, want 1", got)
	}

	if bd.Files.KeyLog == "" {
		t.Fatal("bundle.json records no key log file")
	}
	raw, err := os.ReadFile(filepath.Join(dir, bd.Files.KeyLog))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(raw), hex.EncodeToString(outOfScope[:])) {
		t.Fatal("bundle shipped a key-log line for a session outside its own capture")
	}
	if !strings.Contains(string(raw), hex.EncodeToString(inScope[:])) {
		t.Fatal("bundle dropped a key-log line for a session that IS in its own capture")
	}

	mustVerify(t, dir)
}
