package keylog

import (
	"encoding/hex"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const (
	cr1 = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20"
	cr2 = "a102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1fff"
)

func sampleLog() string {
	return strings.Join([]string{
		"# SSL/TLS secrets log file, generated by the bench",
		"",
		LabelClientHandshake + " " + cr1 + " " + strings.Repeat("11", 32),
		LabelServerHandshake + " " + cr1 + " " + strings.Repeat("22", 32),
		LabelClientTraffic0 + " " + cr1 + " " + strings.Repeat("33", 32),
		LabelServerTraffic0 + " " + cr1 + " " + strings.Repeat("44", 32),
		LabelExporter + " " + cr1 + " " + strings.Repeat("55", 32),
		LabelClientRandom + " " + cr2 + " " + strings.Repeat("66", 48),
		"SOME_FUTURE_SECRET " + cr2 + " " + strings.Repeat("77", 16),
		"",
	}, "\n")
}

func TestParse(t *testing.T) {
	l, err := Parse(strings.NewReader(sampleLog()))
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if l.Len() != 7 {
		t.Fatalf("Len = %d, want 7", l.Len())
	}
	c1, _ := hex.DecodeString(cr1)
	c2, _ := hex.DecodeString(cr2)

	for _, label := range []string{LabelClientHandshake, LabelServerHandshake, LabelClientTraffic0, LabelServerTraffic0, LabelExporter} {
		s, ok := l.Secret(label, c1)
		if !ok || len(s) != 32 {
			t.Errorf("Secret(%s) = %x (ok=%t), want 32 bytes", label, s, ok)
		}
	}
	ms, ok := l.MasterSecret(c2)
	if !ok || len(ms) != 48 {
		t.Fatalf("MasterSecret = %d bytes, ok=%t; want 48", len(ms), ok)
	}
	if _, ok := l.MasterSecret(c1); ok {
		t.Error("session 1 has no master secret and must not report one")
	}

	// An unrecognised label must survive: a bundle written today has to remain
	// readable when a stack starts emitting a secret we have not heard of.
	if s, ok := l.Secret("SOME_FUTURE_SECRET", c2); !ok || len(s) != 16 {
		t.Errorf("unknown label was dropped")
	}

	if !l.Has(c1) || !l.Has(c2) {
		t.Error("Has() should be true for both sessions")
	}
	if l.Has(make([]byte, 32)) {
		t.Error("Has() true for an unknown session")
	}
	if got := l.Sessions(); len(got) != 2 || got[0] != cr1 || got[1] != cr2 {
		t.Errorf("Sessions = %v", got)
	}
	wantLabels := []string{LabelClientHandshake, LabelClientTraffic0, LabelExporter, LabelServerHandshake, LabelServerTraffic0}
	got := l.Labels(c1)
	if strings.Join(got, ",") != strings.Join(wantLabels, ",") {
		t.Errorf("Labels = %v, want %v", got, wantLabels)
	}
	if e := l.Entries(); len(e) != 7 || e[0].Line != 3 {
		t.Errorf("Entries()[0] = %+v", e[0])
	}
}

func TestParseIsCaseInsensitiveOnHex(t *testing.T) {
	upper := LabelClientRandom + " " + strings.ToUpper(cr1) + " " + strings.Repeat("AB", 48)
	l, err := Parse(strings.NewReader(upper))
	if err != nil {
		t.Fatal(err)
	}
	c1, _ := hex.DecodeString(cr1)
	if _, ok := l.MasterSecret(c1); !ok {
		t.Fatal("an upper-case client random must match a lower-case lookup")
	}
}

func TestParseRejectsMalformed(t *testing.T) {
	for _, tc := range []struct {
		name    string
		body    string
		wantErr string
	}{
		{"too few fields", LabelClientRandom + " " + cr1, "want 3"},
		{"too many fields", LabelClientRandom + " " + cr1 + " aabb ccdd", "want 3"},
		{"client random not hex", LabelClientRandom + " zz" + cr1[2:] + " aabb", "not hex"},
		{"secret not hex", LabelClientRandom + " " + cr1 + " nothex", "not hex"},
		{"short client random", LabelClientRandom + " 0102 " + strings.Repeat("11", 48), "want 32"},
		{"empty secret is impossible to encode as hex pairs", LabelClientRandom + " " + cr1 + " \"\"", "not hex"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := Parse(strings.NewReader(tc.body))
			if err == nil || !strings.Contains(err.Error(), tc.wantErr) {
				t.Fatalf("err = %v, want one containing %q", err, tc.wantErr)
			}
			if err != nil && !strings.Contains(err.Error(), "line 1") {
				t.Errorf("err = %q, want it to name the line", err)
			}
		})
	}
}

// TestRSALabelKeepsItsShortKey documents the one label that is NOT keyed by a
// 32-byte client random.
func TestRSALabelKeepsItsShortKey(t *testing.T) {
	l, err := Parse(strings.NewReader(LabelRSA + " 0102030405060708 " + strings.Repeat("cd", 48)))
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if _, ok := l.Secret(LabelRSA, []byte{1, 2, 3, 4, 5, 6, 7, 8}); !ok {
		t.Fatal("the RSA label must be retrievable by its 8-byte key")
	}
}

func TestOpen(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "evidence.keylog")
	if err := os.WriteFile(path, []byte(sampleLog()), 0o600); err != nil {
		t.Fatal(err)
	}
	l, err := Open(path)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	if l.Path() != path {
		t.Errorf("Path = %q", l.Path())
	}
	if l.Len() != 7 {
		t.Errorf("Len = %d", l.Len())
	}
	if _, err := Open(filepath.Join(dir, "absent")); err == nil {
		t.Error("Open of a missing file must fail")
	}
	bad := filepath.Join(dir, "bad.keylog")
	if err := os.WriteFile(bad, []byte("garbage\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := Open(bad); err == nil || !strings.Contains(err.Error(), "bad.keylog") {
		t.Errorf("err = %v, want it to name the file", err)
	}
}
