package tlsserver

import (
	"net"
	"os"
	"path/filepath"
	"testing"
)

// TestMain initializes wolfSSL once per test binary. wolfSSL_Init must
// only be called once per process; doing it from per-test setup would
// be undefined behavior in the underlying C library and would manifest
// as flaky tests or memory corruption that's nightmarish to debug.
//
// This applies to BOTH the unit tests in handlers_test.go and the
// integration tests in server_test.go — they all share this TestMain
// because they share the same package.
func TestMain(m *testing.M) {
	Init()
	code := m.Run()
	Cleanup()
	os.Exit(code)
}

// testdataPath returns an absolute path to a file under the package's
// testdata/ directory. Tests use this rather than relative paths
// because, although `go test` does set CWD to the package directory,
// being explicit prevents surprises if a test ever changes directory.
func testdataPath(rel string) string {
	abs, err := filepath.Abs(filepath.Join("testdata", rel))
	if err != nil {
		panic(err)
	}
	return abs
}

// defaultTestConfig returns a Config pointing at the standard test
// fixtures generated by testdata/gen-test-certs.sh.
func defaultTestConfig() Config {
	return Config{
		CACertPath:     testdataPath("certs/ca-cert.pem"),
		ServerCertPath: testdataPath("certs/server-cert.pem"),
		ServerKeyPath:  testdataPath("certs/server-key.pem"),
		// CipherList left empty → DefaultCipherList
	}
}

// startTestServer creates a Server bound to a random loopback port,
// starts serving in a goroutine, and registers the full teardown
// sequence as a t.Cleanup. The teardown is the trickiest part:
//
//  1. Close the listener so Accept returns net.ErrClosed
//  2. Wait for Serve to actually return (drain the channel)
//  3. Call srv.Close to wait for any in-flight handlers and free ctx
//
// Doing these in the wrong order causes either a hang (Close before
// listener close) or a use-after-free (free ctx while a handler is
// still running).
func startTestServer(t *testing.T, cfg Config) (addr string, srv *Server) {
	t.Helper()

	srv, err := New(cfg)
	if err != nil {
		t.Fatalf("New(%+v): %v", cfg, err)
	}

	lis, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		srv.Close()
		t.Fatalf("Listen: %v", err)
	}

	serveErr := make(chan error, 1)
	go func() {
		serveErr <- srv.Serve(lis)
	}()

	t.Cleanup(func() {
		_ = lis.Close()
		if err := <-serveErr; err != nil {
			t.Errorf("Serve returned error: %v", err)
		}
		srv.Close()
	})

	return lis.Addr().String(), srv
}
