package tlsserver

import (
	"net"
	"os"
	"path/filepath"
	"testing"

	"csip-tls-test/internal/wolfssl"
)

// TestMain initializes wolfSSL once per test binary. wolfSSL_Init must
// only be called once per process; doing it from per-test setup would
// be undefined behavior in the underlying C library.
func TestMain(m *testing.M) {
	wolfssl.Init()
	code := m.Run()
	wolfssl.Cleanup()
	os.Exit(code)
}

// testdataPath returns an absolute path to a file under the package's
// testdata/ directory.
func testdataPath(rel string) string {
	abs, err := filepath.Abs(filepath.Join("testdata", rel))
	if err != nil {
		panic(err)
	}
	return abs
}

// defaultTestConfig returns a Config pointing at the standard test
// fixtures generated by scripts/gen-test-certs.sh.
func defaultTestConfig() Config {
	return Config{
		CACertPath:     testdataPath("certs/ca-cert.pem"),
		ServerCertPath: testdataPath("certs/server-cert.pem"),
		ServerKeyPath:  testdataPath("certs/server-key.pem"),
	}
}

// startTestServer creates a Server bound to a random loopback port,
// starts serving in a goroutine, and registers full teardown via
// t.Cleanup. Teardown order matters: close listener → wait for Serve
// to return → call srv.Close (which waits for in-flight handlers).
func startTestServer(t *testing.T, cfg Config) (addr string, srv *Server) {
	t.Helper()

	srv, err := New(cfg)
	if err != nil {
		t.Fatalf("New(%+v): %v", cfg, err)
	}

	lis, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		srv.Close()
		t.Fatalf("Listen: %v", err)
	}

	serveErr := make(chan error, 1)
	go func() {
		serveErr <- srv.Serve(lis)
	}()

	t.Cleanup(func() {
		_ = lis.Close()
		if err := <-serveErr; err != nil {
			t.Errorf("Serve returned error: %v", err)
		}
		srv.Close()
	})

	return lis.Addr().String(), srv
}
